name: Linux

on: [ push, pull_request, workflow_dispatch ]

jobs:

  # gcc ########################################################################

  gcc-5:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout CXON
      uses: actions/checkout@v1
      with:
        repository: oknenavin/cxon
        ref: master
        path: cxon
    - name: Install CXON
      run: sudo make -C ../cxon install
    - name: Checkout I2O
      uses: actions/checkout@v1
      with:
        path: i2o
    - name: Compiler setup
      run: sudo apt-get update; sudo apt-get install gcc-5 g++-5
    - name: Check
      env:
        CXX: g++-5
        CXXFLAGS: -std=c++11
      run: |
        make -j check
        sudo make install
        stat -t /usr/local/bin/json2cbor
        stat -t /usr/local/bin/json2json
        stat -t /usr/local/bin/cbor2json

  gcc-11:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout CXON
      uses: actions/checkout@v1
      with:
        repository: oknenavin/cxon
        ref: master
        path: cxon
    - name: Install CXON
      run: sudo make -C ../cxon install
    - name: Checkout I2O
      uses: actions/checkout@v1
      with:
        path: i2o
    - name: Compiler setup
      run: sudo apt-get update; sudo apt update; sudo apt install gcc-11 g++-11
    - name: Check
      env:
        CXX: g++-11
        CXXFLAGS: -std=c++20
      run: |
        make -j check
        sudo make install
        stat -t /usr/local/bin/json2cbor
        stat -t /usr/local/bin/json2json
        stat -t /usr/local/bin/cbor2json
  
  # clang ######################################################################

  clang-4:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout CXON
      uses: actions/checkout@v1
      with:
        repository: oknenavin/cxon
        ref: master
        path: cxon
    - name: Install CXON
      run: sudo make -C ../cxon install
    - name: Checkout I2O
      uses: actions/checkout@v1
      with:
        path: i2o
    - name: Compiler setup
      run: sudo apt update; sudo apt install clang-4.0
    - name: Check
      env:
        CXX: clang++-4.0
        CXXFLAGS: -std=c++11
      run: |
        make -j check
        sudo make install
        stat -t /usr/local/bin/json2cbor
        stat -t /usr/local/bin/json2json
        stat -t /usr/local/bin/cbor2json

  clang-12:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout CXON
      uses: actions/checkout@v1
      with:
        repository: oknenavin/cxon
        ref: master
        path: cxon
    - name: Install CXON
      run: sudo make -C ../cxon install
    - name: Checkout I2O
      uses: actions/checkout@v1
      with:
        path: i2o
    - name: Compiler setup
      run: sudo apt-get update; sudo apt-get install clang-11
    - name: Check
      env:
        CXX: clang++-12
        CXXFLAGS: -std=c++20
      run: |
        make -j check
        sudo make install
        stat -t /usr/local/bin/json2cbor
        stat -t /usr/local/bin/json2json
        stat -t /usr/local/bin/cbor2json
