name: Linux

on: [ push, pull_request, workflow_dispatch ]

jobs:

  # gcc ########################################################################

  gcc-10:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout CXON
      uses: actions/checkout@v1
      with:
        repository: oknenavin/cxon
        ref: develop
        path: cxon
    - name: Install CXON
      run: sudo make -C cxon install
    - name: Checkout I2O
      uses: actions/checkout@v1
      with:
        ref: develop
        path: i2o
    - name: Compiler setup
      run: |
        sudo apt-get update
        sudo apt-get install gcc-10 g++-10
    - name: Build I2O
      env:
        CXX: g++-10
        CXXFLAGS: -std=c++17
      run: sudo make -C i2o install
