name: macOS

on: [ push, pull_request, workflow_dispatch ]

jobs:
  
  # xcode ######################################################################
    
  xcode:
    runs-on: macos-latest

    steps:
    - name: Checkout CXON
      uses: actions/checkout@v1
      with:
        repository: oknenavin/cxon
        ref: develop
        path: cxon
    - name: Checkout I2O
      uses: actions/checkout@v1
      with:
        ref: develop
        path: i2o
    - name: Configure
      env:
        CXXFLAGS: -I ../../../cxon/src
      run: cd test ; cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
    - name: Build
      run: cd test ; cmake --build build --parallel
    - name: Check
      run: cd test/build ; ctest -j -V -C Release
